name: Build Il2CppDumper for Termux
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet restore Il2CppDumper/Il2CppDumper.csproj
      - run: dotnet publish Il2CppDumper/Il2CppDumper.csproj -f net8.0 -c Release -r linux-arm64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ./output
      - uses: actions/upload-artifact@v4
        with:
          name: Il2CppDumper-ARM64
          path: ./output/
          retention-days: 30
